In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [11]:
a[2] = 10

In [12]:
a

array([ 1,  2, 10,  4,  5,  6,  7,  8,  9])

In [17]:
np.arange(0.1,0.35, 0.05)

array([0.1 , 0.15, 0.2 , 0.25, 0.3 ])

In [33]:
np.linspace(0,1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-dementional arrays

In [36]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
n = np.array([
    [1,2,3],
    [4,5,6]
])

In [39]:
n[0,1]

2

In [41]:
n[:,1]

array([2, 5])

In [44]:
n[:, 2] = [0,1]
n

array([[1, 2, 0],
       [4, 5, 1]])

### Randomly generated arrays

In [59]:
np.random.seed(2)
np.random.rand(3,4)

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209]])

In [61]:
np.random.seed(2)
10*np.random.randn(3,4) 

array([[ -4.16757847,  -0.56266827, -21.36196096,  16.40270808],
       [-17.93435585,  -8.41747366,   5.02881417, -12.45288087],
       [-10.57952219,  -9.09007615,   5.51454045,  22.92208013]])

In [74]:
np.random.seed(2)
np.random.randint(1,4, (2,2))

array([[1, 2],
       [1, 3]])

### Element-wise operations

In [76]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [77]:
a+1

array([1, 2, 3, 4, 5])

In [78]:
a*2

array([0, 2, 4, 6, 8])

In [79]:
(10 + (a*2))

array([10, 12, 14, 16, 18])

### Comparison operations

In [80]:
a >= 2

array([False, False,  True,  True,  True])

In [89]:
b = a*1.2

In [90]:
a > b

array([False, False, False, False, False])

In [92]:
a[a>2]

array([3, 4])

### Summarizing operations

In [93]:
a.min()

0

In [94]:
a.max()

4

In [95]:
a.sum()

10

In [96]:
a.mean()

2.0

In [97]:
a.std()

1.4142135623730951

In [99]:
n

array([[1, 2, 0],
       [4, 5, 1]])

In [100]:
n.sum()

13

In [102]:
n.max()

5

## Linear algebra

In [103]:
u = np.array([1,2,3])
v = np.array([4,5,6])

In [104]:
u+v

array([5, 7, 9])

In [106]:
# Vector-vector multiplication
# dot product
u.dot(v)

32

In [110]:
def vec_vec_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    results = 0.0
    n = u.shape[0]
    for i in range(n):  
         results = results + u[i] * v[i]
    return results

In [111]:
vec_vec_multiplication(u, v)

32.0

In [112]:
# Matrix-vector multiplication
matrix_a = np.random.randint(1,16, (4,4))

In [115]:
new_v = np.array([1,2,3,4])

In [116]:
matrix_a.dot(new_v)

array([90, 68, 95, 57])

In [118]:
def matrix_vector_multiply(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vec_vec_multiplication(U[i], v)
    return result

In [119]:
matrix_vector_multiply(matrix_a, new_v)

array([90., 68., 95., 57.])

In [120]:
# Matrix-matrix multiplicaton
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [122]:
V = np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [123]:
U.dot(V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [124]:
def matrix_matrix_miltiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiply(U, vi)
        result[:, i] = Uvi
    return result

In [125]:
matrix_matrix_miltiplication(U, V)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [ ]:
# Identity matrix I [ones]
""" 
[1 0 0
 0 1 0
 0 0 1]
U*I = U
"""

In [126]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [139]:
# Matrix inverse
#Only square matrix has inverse
Vs = V[[0,1,2]]

Vs_inv = np.linalg.inv(Vs)

In [140]:
Vs_inv.dot(Vs)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])